bind:
  image: vtbru/bind:latest

  volumes:
    # You must provide a config file
    - ./named.conf:/etc/bind/named.conf
    - ./rndc.conf:/etc/bind/rndc.conf

  ports:
    - "53:53/tcp"
    - "53:53/udp"
    