bind:
  image: vtbru/bind:latest
  restart: unless-stopped
  volumes:
    - ./named.conf:/etc/bind/named.conf
    - ./rndc.conf:/etc/bind/rndc.conf
  ports:
    - "53:53/tcp"
    - "53:53/udp"
  container_name: bind